language: android
cache: bundler
rvm: 2.3.7

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-16
    - android-27
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-16

env:
  matrix:
    - ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=5 # increase from default of 2 mins

# see https://github.com/travis-ci/travis-ci/issues/8874
before_install:
  - yes | sdkmanager "platforms;android-27"
  - bundle install

before_script:
  # Create and start emulator
  - android list targets
  - jdk_switcher use oraclejdk8
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
  - adb shell input keyevent 82 &

script: bundle exec maze-runner -c

sudo: false
